#!/usr/bin/env python3
"""Interactive CAM4 hand ROI selector backed by the live compressed stream."""

import argparse
from contextlib import contextmanager
import fcntl
import hashlib
import json
import math
import os
from pathlib import Path
import subprocess
import tempfile
import time

import yaml


ROI_KEYS = (
    'region_x_min',
    'region_x_max',
    'region_y_min',
    'region_y_max',
)
FULL_FRAME_ROI = (0.0, 1.0, 0.0, 1.0)


def validate_normalized_roi(roi):
    """Return a validated normalized ROI tuple (xmin, xmax, ymin, ymax)."""
    if len(roi) != 4:
        raise ValueError('ROI must contain four values')
    values = tuple(float(value) for value in roi)
    if not all(math.isfinite(value) for value in values):
        raise ValueError('ROI values must be finite')
    x_min, x_max, y_min, y_max = values
    if not (0.0 <= x_min < x_max <= 1.0):
        raise ValueError('ROI must satisfy 0 <= x_min < x_max <= 1')
    if not (0.0 <= y_min < y_max <= 1.0):
        raise ValueError('ROI must satisfy 0 <= y_min < y_max <= 1')
    return values


def pixel_box_to_normalized(box, width, height, min_size_px=32):
    """Convert a drag box to a clamped, validated normalized ROI."""
    if width <= 0 or height <= 0:
        raise ValueError('image dimensions must be positive')
    x0, y0, x1, y1 = (float(value) for value in box)
    # Mouse coordinates are inclusive source-image pixel indices. Convert the
    # far edge to an exclusive bound so selecting the final pixel reaches 1.0.
    left = max(0.0, min(min(x0, x1), width - 1))
    right = max(0.0, min(max(x0, x1) + 1.0, width))
    top = max(0.0, min(min(y0, y1), height - 1))
    bottom = max(0.0, min(max(y0, y1) + 1.0, height))
    minimum_width = max(float(min_size_px), width * 0.02)
    minimum_height = max(float(min_size_px), height * 0.02)
    if right - left < minimum_width or bottom - top < minimum_height:
        raise ValueError(
            f'ROI is too small; minimum is {minimum_width:.0f}x'
            f'{minimum_height:.0f} pixels')
    return validate_normalized_roi((
        left / width,
        right / width,
        top / height,
        bottom / height,
    ))


def normalized_to_pixel_box(roi, width, height):
    x_min, x_max, y_min, y_max = validate_normalized_roi(roi)
    return (
        int(round(x_min * width)),
        int(round(y_min * height)),
        min(width - 1, int(round(x_max * width))),
        min(height - 1, int(round(y_max * height))),
    )


def load_roi_config(path):
    path = Path(path)
    if not path.exists():
        return FULL_FRAME_ROI
    payload = yaml.safe_load(path.read_text(encoding='utf-8')) or {}
    try:
        params = payload['/**']['ros__parameters']
        roi = tuple(params[key] for key in ROI_KEYS)
    except (KeyError, TypeError) as exc:
        raise ValueError(f'invalid CAM4 ROI config: {exc}') from exc
    return validate_normalized_roi(roi)


def config_sha256(path):
    path = Path(path)
    if not path.exists():
        return None
    if path.is_symlink() or not path.is_file():
        raise ValueError('CAM4 ROI config must be a regular, non-symlink file')
    return hashlib.sha256(path.read_bytes()).hexdigest()


@contextmanager
def exclusive_selector_lock(config_path):
    """Prevent two selector instances from racing the same ROI policy."""
    runtime_dir = Path(os.environ.get('XDG_RUNTIME_DIR', '/tmp'))
    lock_name = hashlib.sha256(
        str(Path(config_path).resolve()).encode('utf-8')).hexdigest()[:16]
    lock_path = runtime_dir / f'cam4_hand_roi_selector_{lock_name}.lock'
    lock_handle = lock_path.open('a+', encoding='utf-8')
    try:
        fcntl.flock(lock_handle.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
    except BlockingIOError as exc:
        lock_handle.close()
        raise RuntimeError('another CAM4 ROI selector is already running') from exc
    try:
        yield config_sha256(config_path)
    finally:
        fcntl.flock(lock_handle.fileno(), fcntl.LOCK_UN)
        lock_handle.close()


def render_roi_config(roi, *, image_width=None, image_height=None):
    x_min, x_max, y_min, y_max = validate_normalized_roi(roi)
    pixel_note = ''
    if image_width and image_height:
        pixel_box = normalized_to_pixel_box(roi, image_width, image_height)
        pixel_note = (
            f'# Selected on {image_width}x{image_height}: '
            f'x={pixel_box[0]}..{pixel_box[2]}, '
            f'y={pixel_box[1]}..{pixel_box[3]}\n')
    return (
        '# CAM4 hand-selection ROI. Generated by '
        'scripts/select_cam4_hand_roi.py.\n'
        '# A detected hand is retained when the mean of its 21 landmarks is '
        'inside\n'
        '# this inclusive, normalized rectangle.\n'
        f'{pixel_note}'
        '/**:\n'
        '  ros__parameters:\n'
        f'    region_x_min: {x_min:.6f}\n'
        f'    region_x_max: {x_max:.6f}\n'
        f'    region_y_min: {y_min:.6f}\n'
        f'    region_y_max: {y_max:.6f}\n'
    )


def write_roi_config_atomic(path, roi, *, image_width=None, image_height=None,
                            expected_sha256=None):
    """Atomically replace only the dedicated CAM4 ROI parameter file."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    config_sha256(path)
    content = render_roi_config(
        roi, image_width=image_width, image_height=image_height)
    parsed = yaml.safe_load(content)
    params = parsed['/**']['ros__parameters']
    if set(params) != set(ROI_KEYS):
        raise ValueError('generated ROI config contains unexpected parameters')
    validate_normalized_roi(tuple(params[key] for key in ROI_KEYS))
    previous_mode = path.stat().st_mode & 0o777 if path.exists() else 0o644
    fd, temporary_name = tempfile.mkstemp(
        prefix=f'.{path.name}.', suffix='.tmp', dir=path.parent)
    try:
        with os.fdopen(fd, 'w', encoding='utf-8') as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(temporary_name, previous_mode)
        if (
            expected_sha256 is not None
            and config_sha256(path) != expected_sha256
        ):
            raise RuntimeError(
                'CAM4 ROI config changed while the selector was open; '
                'nothing was overwritten')
        os.replace(temporary_name, path)
        directory_fd = os.open(path.parent, os.O_RDONLY)
        try:
            os.fsync(directory_fd)
        finally:
            os.close(directory_fd)
    except Exception:
        try:
            os.unlink(temporary_name)
        except FileNotFoundError:
            pass
        raise


def _draw_text(cv2, image, text, origin, color=(255, 255, 255)):
    x, y = origin
    cv2.putText(
        image, text, (x, y), cv2.FONT_HERSHEY_SIMPLEX, 0.64,
        (0, 0, 0), 4, cv2.LINE_AA)
    cv2.putText(
        image, text, (x, y), cv2.FONT_HERSHEY_SIMPLEX, 0.64,
        color, 1, cv2.LINE_AA)


def _run_selector_locked(args, original_config_sha256):
    import cv2
    import numpy as np
    import rclpy
    from rclpy.node import Node
    from rclpy.qos import qos_profile_sensor_data
    from sensor_msgs.msg import CompressedImage

    window_name = 'CAM4 Hand ROI Selector'
    current_roi = load_roi_config(args.config)
    state = {
        'frame': None,
        'frame_received_at': None,
        'latest_jpeg': None,
        'latest_frame_id': '',
        'latest_seq': 0,
        'decoded_seq': 0,
        'drag_start': None,
        'drag_now': None,
        'drag_frame': None,
        'pending_roi': None,
        'pending_shape': None,
        'status': 'Waiting for live CAM4 frame...',
    }

    class FrameSubscriber(Node):
        def __init__(self):
            super().__init__('cam4_hand_roi_selector')
            self.create_subscription(
                CompressedImage, args.topic, self._on_frame,
                qos_profile_sensor_data)

        def _on_frame(self, message):
            state['latest_jpeg'] = bytes(message.data)
            state['latest_frame_id'] = str(message.header.frame_id)
            state['latest_seq'] += 1

    def on_mouse(event, x, y, _flags, _userdata):
        frame = state['frame']
        if frame is None:
            return
        if event == cv2.EVENT_LBUTTONDOWN:
            state['drag_start'] = (x, y)
            state['drag_now'] = (x, y)
            state['drag_frame'] = frame.copy()
            state['pending_roi'] = None
            state['pending_shape'] = None
            state['status'] = 'Dragging ROI...'
        elif event == cv2.EVENT_MOUSEMOVE and state['drag_start'] is not None:
            state['drag_now'] = (x, y)
        elif event == cv2.EVENT_LBUTTONUP and state['drag_start'] is not None:
            start = state['drag_start']
            state['drag_now'] = (x, y)
            state['drag_start'] = None
            drag_frame = state['drag_frame']
            height, width = drag_frame.shape[:2]
            try:
                state['pending_roi'] = pixel_box_to_normalized(
                    (*start, x, y), width, height,
                    min_size_px=args.min_size_px)
            except ValueError as exc:
                state['pending_roi'] = None
                state['pending_shape'] = None
                state['status'] = str(exc)
            else:
                state['pending_shape'] = (height, width)
                state['status'] = 'ROI ready. ENTER saves; ESC cancels.'
            state['drag_frame'] = None

    rclpy.init()
    node = FrameSubscriber()
    cv2.namedWindow(window_name, cv2.WINDOW_AUTOSIZE)
    cv2.setMouseCallback(window_name, on_mouse)
    try:
        cv2.setWindowProperty(window_name, cv2.WND_PROP_TOPMOST, 1)
        cv2.moveWindow(window_name, 240, 150)
    except cv2.error:
        pass

    saved_roi = None
    saved_shape = None
    started_at = time.monotonic()
    try:
        while rclpy.ok():
            rclpy.spin_once(node, timeout_sec=0.01)
            if state['decoded_seq'] != state['latest_seq']:
                state['decoded_seq'] = state['latest_seq']
                if state['latest_frame_id'] != args.expected_frame_id:
                    state['status'] = (
                        'Unexpected frame_id: '
                        f'{state["latest_frame_id"] or "<empty>"}')
                else:
                    decoded = cv2.imdecode(
                        np.frombuffer(state['latest_jpeg'], dtype=np.uint8),
                        cv2.IMREAD_COLOR)
                    if decoded is None:
                        state['status'] = 'Corrupt JPEG received; waiting...'
                    else:
                        old_shape = (
                            None if state['frame'] is None
                            else state['frame'].shape[:2])
                        new_shape = decoded.shape[:2]
                        state['frame'] = decoded
                        state['frame_received_at'] = time.monotonic()
                        if (
                            state['pending_shape'] is not None
                            and state['pending_shape'] != new_shape
                        ):
                            state['pending_roi'] = None
                            state['pending_shape'] = None
                            state['status'] = (
                                'Resolution changed; draw the ROI again.')
                        elif state['status'].startswith('Waiting'):
                            state['status'] = (
                                'Drag a rectangle, then press ENTER.')
                        elif old_shape is not None and old_shape != new_shape:
                            state['status'] = (
                                'Resolution changed; draw the ROI again.')

            frame = (
                state['drag_frame']
                if state['drag_start'] is not None
                else state['frame'])
            if frame is None:
                canvas = np.zeros((540, 960, 3), dtype=np.uint8)
                _draw_text(
                    cv2, canvas, 'Waiting for live CAM4 frame...', (28, 60),
                    (0, 220, 255))
                _draw_text(cv2, canvas, 'ESC: cancel', (28, 100))
                if time.monotonic() - started_at > args.first_frame_timeout_sec:
                    print(json.dumps({
                        'status': 'error',
                        'error': 'no valid live CAM4 frame received',
                    }), flush=True)
                    return 1
            else:
                canvas = frame.copy()
                height, width = canvas.shape[:2]
                display_roi = state['pending_roi'] or current_roi
                x0, y0, x1, y1 = normalized_to_pixel_box(
                    display_roi, width, height)
                color = ((0, 220, 255) if state['pending_roi']
                         else (80, 255, 120))
                cv2.rectangle(canvas, (x0, y0), (x1, y1), color, 3)
                if state['drag_start'] is not None and state['drag_now']:
                    cv2.rectangle(
                        canvas, state['drag_start'], state['drag_now'],
                        (0, 220, 255), 2)
                cv2.rectangle(canvas, (0, 0), (width, 82), (20, 20, 20), -1)
                _draw_text(
                    cv2, canvas,
                    'Drag: set ROI | ENTER: save+restart | R: full frame | ESC: cancel',
                    (14, 29))
                _draw_text(
                    cv2, canvas,
                    'Keep rule: mean center of 21 hand landmarks must be inside.',
                    (14, 57), (180, 230, 255))
                _draw_text(cv2, canvas, state['status'], (14, 79), color)
                fresh = (
                    state['frame_received_at'] is not None
                    and time.monotonic() - state['frame_received_at']
                    < args.stale_timeout_sec)
                if not fresh:
                    _draw_text(
                        cv2, canvas, 'LIVE FRAME STALE - save disabled',
                        (14, 110), (0, 0, 255))

            cv2.imshow(window_name, canvas)
            key = cv2.waitKey(16) & 0xFF
            if key == 27:
                print(json.dumps({'status': 'cancelled'}), flush=True)
                return 0
            if key in (ord('r'), ord('R')) and frame is not None:
                state['pending_roi'] = FULL_FRAME_ROI
                state['pending_shape'] = frame.shape[:2]
                state['drag_start'] = None
                state['drag_now'] = None
                state['drag_frame'] = None
                state['status'] = 'Full-frame ROI ready. ENTER saves.'
            if key in (10, 13) and frame is not None:
                fresh = (
                    state['frame_received_at'] is not None
                    and time.monotonic() - state['frame_received_at']
                    < args.stale_timeout_sec)
                if not fresh:
                    state['status'] = 'Live frame is stale; cannot save.'
                    continue
                if state['pending_roi'] is None:
                    state['status'] = 'Drag a new ROI or press R first.'
                    continue
                if state['pending_shape'] != state['frame'].shape[:2]:
                    state['pending_roi'] = None
                    state['pending_shape'] = None
                    state['status'] = 'Resolution changed; draw the ROI again.'
                    continue
                saved_roi = state['pending_roi']
                saved_shape = state['pending_shape']
                break
            try:
                if cv2.getWindowProperty(window_name, cv2.WND_PROP_VISIBLE) < 1:
                    print(json.dumps({'status': 'cancelled'}), flush=True)
                    return 0
            except cv2.error:
                print(json.dumps({'status': 'cancelled'}), flush=True)
                return 0
    finally:
        node.destroy_node()
        rclpy.shutdown()
        cv2.destroyAllWindows()

    height, width = saved_shape
    try:
        write_roi_config_atomic(
            args.config, saved_roi, image_width=width, image_height=height,
            expected_sha256=original_config_sha256)
    except (OSError, RuntimeError, ValueError) as exc:
        print(json.dumps({
            'status': 'error',
            'error': str(exc),
        }, ensure_ascii=False), flush=True)
        return 1
    result = {
        'status': 'saved',
        'config': str(Path(args.config).resolve()),
        'roi': {
            key: round(value, 6)
            for key, value in zip(ROI_KEYS, saved_roi)
        },
        'image_size': {'width': width, 'height': height},
    }
    if args.restart_service:
        restart_services, completed = restart_user_services(
            args.restart_service)
        result['restart_services'] = restart_services
        result['restart_returncode'] = completed.returncode
        if completed.returncode != 0:
            result['status'] = 'saved_restart_failed'
            result['restart_error'] = completed.stderr.strip()
            print(json.dumps(result, ensure_ascii=False), flush=True)
            return 1
    print(json.dumps(result, ensure_ascii=False), flush=True)
    return 0


def run_selector(args):
    try:
        with exclusive_selector_lock(args.config) as original_config_sha256:
            return _run_selector_locked(args, original_config_sha256)
    except (OSError, RuntimeError, ValueError) as exc:
        print(json.dumps({
            'status': 'error',
            'error': str(exc),
        }, ensure_ascii=False), flush=True)
        return 1


def restart_user_services(service_names):
    """Restart each requested user unit once, in one systemd transaction."""
    services = list(dict.fromkeys(
        str(name).strip() for name in service_names if str(name).strip()))
    if not services:
        return services, None
    completed = subprocess.run(
        ['systemctl', '--user', 'restart', *services],
        text=True,
        capture_output=True,
    )
    return services, completed


def parse_args():
    root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        '--topic',
        default='/perception/ingress/cam_4/color/image_raw/compressed')
    parser.add_argument(
        '--config', default=str(root / 'config' / 'cam4_hand_roi.yaml'))
    parser.add_argument('--min-size-px', type=int, default=32)
    parser.add_argument(
        '--expected-frame-id', default='cam_4_color_optical_frame')
    parser.add_argument('--stale-timeout-sec', type=float, default=0.5)
    parser.add_argument('--first-frame-timeout-sec', type=float, default=5.0)
    parser.add_argument(
        '--restart-service', action='append', default=[])
    return parser.parse_args()


if __name__ == '__main__':
    raise SystemExit(run_selector(parse_args()))
